package com.silicon.agentflow.util;

import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

/**
 * TCL 配置文件生成器
 * 根据 JSON 参数动态生成 OpenROAD 配置文件
 */
@Slf4j
public class TclTemplateGenerator {

    // TCL 模板内容
    private static final String TCL_TEMPLATE = """
            # OpenROAD Configuration
            # Generated by Silicon-Agent-Flow

            # Design Parameters
            set design_name "{design_name}"
            set technology "{technology}"

            # Floorplan Parameters
            set utilization {utilization}
            set aspect_ratio {aspect_ratio}
            set core_margin {core_margin}

            # Timing Parameters
            set target_frequency {target_frequency}
            set clock_period [expr 1000.0 / $target_frequency]

            # Power Parameters
            set power_budget {power_budget}

            puts "========================================="
            puts "Design: $design_name"
            puts "Technology: $technology"
            puts "Utilization: $utilization"
            puts "Aspect Ratio: $aspect_ratio"
            puts "Target Frequency: $target_frequency MHz"
            puts "Clock Period: $clock_period ns"
            puts "========================================="

            # Simulate OpenROAD execution
            # In real scenario, this would call actual OpenROAD commands

            # Mock results for demonstration
            set total_area [expr 1000.0 + rand() * 4000.0]
            set total_power [expr 50.0 + rand() * 150.0]
            set actual_freq [expr $target_frequency * (0.9 + rand() * 0.2)]

            puts ""
            puts "========== Results =========="
            puts "Total Area: $total_area um2"
            puts "Total Power: $total_power mW"
            puts "Frequency: $actual_freq MHz"
            puts "Core Utilization: $utilization %"
            puts "============================="

            exit 0
            """;

    /**
     * 生成 TCL 配置文件
     *
     * @param jobId 任务 ID
     * @param parameters JSON 参数
     * @return 生成的文件路径
     */
    public static Path generateTclConfig(Long jobId, Map<String, Object> parameters) throws IOException {
        log.info("Generating TCL config for job {}", jobId);

        // 提取参数，设置默认值
        String designName = getStringParam(parameters, "design_name", "chip_design");
        String technology = getStringParam(parameters, "technology", "28nm");
        double utilization = getDoubleParam(parameters, "utilization", 65.0);
        double aspectRatio = getDoubleParam(parameters, "aspect_ratio", 1.0);
        double coreMargin = getDoubleParam(parameters, "core_margin", 2.0);
        double targetFrequency = getDoubleParam(parameters, "target_frequency", 1000.0);
        double powerBudget = getDoubleParam(parameters, "power_budget", 100.0);

        // 替换模板中的占位符
        String tclContent = TCL_TEMPLATE
                .replace("{design_name}", designName)
                .replace("{technology}", technology)
                .replace("{utilization}", String.valueOf(utilization))
                .replace("{aspect_ratio}", String.valueOf(aspectRatio))
                .replace("{core_margin}", String.valueOf(coreMargin))
                .replace("{target_frequency}", String.valueOf(targetFrequency))
                .replace("{power_budget}", String.valueOf(powerBudget));

        // 创建工作目录
        Path workDir = Paths.get("work", "job_" + jobId);
        Files.createDirectories(workDir);

        // 写入文件
        Path tclFile = workDir.resolve("config.tcl");
        Files.writeString(tclFile, tclContent);

        log.info("TCL config generated at: {}", tclFile.toAbsolutePath());
        return tclFile;
    }

    /**
     * 获取字符串参数
     */
    private static String getStringParam(Map<String, Object> params, String key, String defaultValue) {
        Object value = params.get(key);
        return value != null ? value.toString() : defaultValue;
    }

    /**
     * 获取数值参数
     */
    private static double getDoubleParam(Map<String, Object> params, String key, double defaultValue) {
        Object value = params.get(key);
        if (value == null) {
            return defaultValue;
        }
        if (value instanceof Number) {
            return ((Number) value).doubleValue();
        }
        try {
            return Double.parseDouble(value.toString());
        } catch (NumberFormatException e) {
            log.warn("Invalid number format for {}: {}, using default {}", key, value, defaultValue);
            return defaultValue;
        }
    }

    /**
     * 清理工作目录
     */
    public static void cleanupWorkDir(Long jobId) {
        try {
            Path workDir = Paths.get("work", "job_" + jobId);
            if (Files.exists(workDir)) {
                Files.walk(workDir)
                        .sorted((a, b) -> -a.compareTo(b))
                        .forEach(path -> {
                            try {
                                Files.delete(path);
                            } catch (IOException e) {
                                log.warn("Failed to delete {}", path, e);
                            }
                        });
                log.info("Cleaned up work directory for job {}", jobId);
            }
        } catch (IOException e) {
            log.error("Failed to cleanup work directory for job {}", jobId, e);
        }
    }
}
